# TOKEN_MAPPING for available perp platforms and on‐chain DEX contracts

TOKEN_MAPPING = {
    "Fartcoin": {
        "drift":        True,
        "dydx":         True,
        "hyperliquid":  True,
        "gmx":          True,
        "sol":          "9BB6NFEcjBCtnNLFko2FqVQBq8HHM13kCyYcdQbgpump",
        "eth":          None,
        "base":         None,
    },
    "Bonk": {
        "drift":        True,
        "dydx":         True,
        "hyperliquid":  True,
        "gmx":          True,
        "sol":          "DezXAZ8z7PnrnRJjz3wXBoRgixCa6xjnB7YaB1pPB263",
        "eth":          "0x1151cb3d861920e07a38e03eead12c32178567f6",
        "base":         None,
    },
    "PEPE": {
        "drift":        True,
        "dydx":         True,
        "hyperliquid":  True,
        "gmx":          True,
        "sol":          None,
        "eth":          "0x6982508145454ce325ddbe47a25d4ec3d2311933",
        "base":         None,
    },
    "TRUMP": {
        "drift":        True,
        "dydx":         True,
        "hyperliquid":  True,
        "gmx":          True,
        "sol":          "6p6xgHyF7AeE6TZkSmFsko444wqoP15icUSqi2jfGiPN",
        "eth":          None,
        "base":         None,
    },
    "JUP": {
        "drift":        True,
        "dydx":         True,
        "hyperliquid":  True,
        "gmx":          True,
        "sol":          "JUPyiwrYJFskUPiHa7hkeR8VUtAeFoSYbKedZNsDvCN",
        "eth":          None,
        "base":         None,
    },
    "W": {
        "drift":        True,
        "dydx":         True,
        "hyperliquid":  True,
        "gmx":          False,
        "sol":          "85VBFQZC9TZkfaptBWjvUw7YbZjy52A6mjtPGjstQAmQ",
        "eth":          "0xb0ffa8000886e57f86dd5264b9582b2ad87b2b91",
        "base":         "0xb0ffa8000886e57f86dd5264b9582b2ad87b2b91",
    },
    "PNUT": {
        "drift":        True,
        "dydx":         True,
        "hyperliquid":  True,
        "gmx":          False,
        "sol":          "2qEHjDLDLbuBgRYvsxhc5D6uDWAivNFZGan56P1tpump",
        "eth":          None,
        "base":         None,
    },
    "AI16Z": {
        "drift":        True,
        "dydx":         True,
        "hyperliquid":  True,
        "gmx":          True,
        "sol":          "HeLp6NuQkmYB4pYWo2zYs22mESHXPQYzXbB8n4V98jwC",
        "eth":          None,
        "base":         None,
    },
    "MELANIA": {
        "drift":        True,
        "dydx":         True,
        "hyperliquid":  True,
        "gmx":          True,
        "sol":          "FUAfBo2jgks6gB4Z4LfZkqSZgzNucisEHqnNebaRxM1P",
        "eth":          None,
        "base":         None,
    },
    "KMNO": {
        "drift":        True,
        "dydx":         True,
        "hyperliquid":  False,
        "gmx":          False,
        "sol":          "KMNo3nJsBXfcpJTVhZcXLW7RmTwTt4GVFE7suUBo9sS",
        "eth":          None,
        "base":         None,
    },
    "FWOG": {
        "drift":        True,
        "dydx":         True,
        "hyperliquid":  False,
        "gmx":          False,
        "sol":          "A8C3xuqscfmyLrte3VmTqrAq8kgMASius9AFNANwpump",
        "eth":          None,
        "base":         None,
    },
    "MOODENG": {
        "drift":        True,
        "dydx":         True,
        "hyperliquid":  True,
        "gmx":          False,
        "sol":          "ED5nyyWEzpPPiWimP8vYm7sD7TD3LAt3Q3gRTWHzPJBY",
        "eth":          None,
        "base":         None,
    },
    "JTO": {
        "drift":        True,
        "dydx":         True,
        "hyperliquid":  True,
        "gmx":          False,
        "sol":          "jtojtomepa8beP8AuQc6eXt5FriJwfFMwQx2v2f9mCL",
        "eth":          None,
        "base":         None,
    },
    "GOAT": {
        "drift":        True,
        "dydx":         True,
        "hyperliquid":  True,
        "gmx":          False,
        "sol":          "CzLSujWBLFsSjncfkh59rUFqvafWcY5tzedWJSuypump",
        "eth":          None,
        "base":         None,
    },
    "SPX": {
        "drift":        False,
        "dydx":         True,
        "hyperliquid":  True,
        "gmx":          False,
        "sol":          "J3NKxxXZcnNiMjKw9hYb2K4LUxgwB6t1FtPtQVsv3KFr",
        "eth":          "0xe0f63a424a4439cbe457d80e4f4b51ad25b2c56c",
        "base":         "0x50da645f148798f68ef2d7db7c1cb22a6819bb2c",
    },
    "AIXBT": {
        "drift":        False,
        "dydx":         True,
        "hyperliquid":  True,
        "gmx":          True,
        "sol":          "14zP2ToQ79XWvc7FQpm4bRnp9d6Mp1rFfsUW3gpLcRX",
        "eth":          None,
        "base":         "0x4f9fd6be4a90f2620860d680c0d4d5fb53d1a825",
    },
    "GRIFFAIN": {
        "drift":        False,
        "dydx":         True,
        "hyperliquid":  True,
        "gmx":          False,
        "sol":          "KENJSUYLASHUMfHyy5o4Hp2FdNqZg1AsUPhfH2kYvEP",
        "eth":          None,
        "base":         None,
    },
    "VIRTUAL": {
        "drift":        False,
        "dydx":         True,
        "hyperliquid":  True,
        "gmx":          True,
        "sol":          "3iQL8BFS2vE7mww4ehAqQHAsbmRNCrPxizWAT2Zfyr9y",
        "eth":          "0x44ff8620b8ca30902395a7bd3f2407e1a091bf73",
        "base":         "0x0b3e328455c4059eeb9e3f84b5543f74e24e7e1b",
    },
    "VINE": {
        "drift":        False,
        "dydx":         True,
        "hyperliquid":  True,
        "gmx":          False,
        "sol":          "6AJcP7wuLwmRYLBNbi825wgguaPsWzPBEHcHndpRpump",
        "eth":          None,
        "base":         None,
    },
    "BANANA": {
        "drift":        False,
        "dydx":         True,
        "hyperliquid":  True,
        "gmx":          False,
        "sol":          None,
        "eth":          "0x38e68a37e401f7271568cecaac63c6b1e19130b4",
        "base":         None,
    },
    "CHILLGUY": {
        "drift":        False,
        "dydx":         False,
        "hyperliquid":  True,
        "gmx":          False,
        "sol":          "Df6yfrKC8kZE3KNkrHERKzAetSxbrWeniQfyJY4Jpump",
        "eth":          None,
        "base":         None,
    }
}