# TOKEN_MAPPING for available perp platforms and on‐chain DEX contracts

TOKEN_MAPPING = {
    "FARTCOIN": {
        "drift":        None,
        "dydx":         "FARTCOIN,RAYDIUM,9BB6NFECJBCTNNLFKO2FQVQBQ8HHM13KCYYCDQBGPUMP-USD",
        "hyperliquid":  "FARTCOIN",
        "sol":          "9BB6NFEcjBCtnNLFko2FqVQBq8HHM13kCyYcdQbgpump",
        "eth":          None,
        "base":         None,
        "max_price": 2.48,
    },
    "BONK": {
        "drift":        "1MBONK-PERP",
        "dydx":         "BONK-USD",
        "hyperliquid":  "kBONK",
        "sol":          "DezXAZ8z7PnrnRJjz3wXBoRgixCa6xjnB7YaB1pPB263",
        "eth":          "0x1151cb3d861920e07a38e03eead12c32178567f6",
        "base":         None,
        "max_price": 0.00005825,
    },
    "PEPE": {
        "drift":        "1MPEPE-PERP",
        "dydx":         "PEPE-USD",
        "hyperliquid":  "kPEPE",
        "sol":          None,
        "eth":          "0x6982508145454ce325ddbe47a25d4ec3d2311933",
        "base":         None,
        "max_price": 0.00002803,
    },
    "TRUMP": {
        "drift":        "TRUMP-PERP",
        "dydx":         "TRUMP-USD",
        "hyperliquid":  "TRUMP",
        "sol":          "6p6xgHyF7AeE6TZkSmFsko444wqoP15icUSqi2jfGiPN",
        "eth":          None,
        "base":         None,
        "max_price": 73.43,
    },
    "JUP": {
        "drift":        "JUP-PERP",
        "dydx":         "JUP-USD",
        "hyperliquid":  "JUP",
        "sol":          "JUPyiwrYJFskUPiHa7hkeR8VUtAeFoSYbKedZNsDvCN",
        "eth":          None,
        "base":         None,
        "max_price": 2.0,
    },
    "W": {
        "drift":        "W-PERP",
        "dydx":         "W-USD",
        "hyperliquid":  "W",
        "sol":          "85VBFQZC9TZkfaptBWjvUw7YbZjy52A6mjtPGjstQAmQ",
        "eth":          "0xb0ffa8000886e57f86dd5264b9582b2ad87b2b91",
        "base":         "0xb0ffa8000886e57f86dd5264b9582b2ad87b2b91",
        "max_price": 1.66,
    },
    "PNUT": {
        "drift":        "PNUT-PERP",
        "dydx":         "PNUT-USD",
        "hyperliquid":  "PNUT",
        "sol":          "2qEHjDLDLbuBgRYvsxhc5D6uDWAivNFZGan56P1tpump",
        "eth":          None,
        "base":         None,
        "max_price": 2.44,
    },
    "AI16Z": {
        "drift":        "AI16Z-PERP",
        "dydx":         "AI16Z-USD",
        "hyperliquid":  "AI16Z",
        "sol":          "HeLp6NuQkmYB4pYWo2zYs22mESHXPQYzXbB8n4V98jwC",
        "eth":          None,
        "base":         None,
        "max_price": 2.47,
    },
    "MELANIA": {
        "drift":        "MELANIA-PERP",
        "dydx":         "MELANIA-USD",
        "hyperliquid":  "MELANIA",
        "sol":          "FUAfBo2jgks6gB4Z4LfZkqSZgzNucisEHqnNebaRxM1P",
        "eth":          None,
        "base":         None,
        "max_price": 13.05,
    },
    "KMNO": {
        "drift":        "KMNO-PERP",
        "dydx":         None,
        "hyperliquid":  None,
        "sol":          "KMNo3nJsBXfcpJTVhZcXLW7RmTwTt4GVFE7suUBo9sS",
        "eth":          None,
        "base":         None,
        "max_price": 0.2478,
    },
    "FWOG": {
        "drift":        "FWOG-PERP",
        "dydx":         None,
        "hyperliquid":  None,
        "sol":          "A8C3xuqscfmyLrte3VmTqrAq8kgMASius9AFNANwpump",
        "eth":          None,
        "base":         None,
        "max_price": 0.009244,
    },
    "MOODENG": {
        "drift":        "MOODENG-PERP",
        "dydx":         "MOODENG-USD",
        "hyperliquid":  "MOODENG",
        "sol":          "ED5nyyWEzpPPiWimP8vYm7sD7TD3LAt3Q3gRTWHzPJBY",
        "eth":          None,
        "base":         None,
        "max_price": 0.6804,
    },
    "JTO": {
        "drift":        "JTO-PERP",
        "dydx":         "JTO-USD",
        "hyperliquid":  "JTO",
        "sol":          "jtojtomepa8beP8AuQc6eXt5FriJwfFMwQx2v2f9mCL",
        "eth":          None,
        "base":         None,
        "max_price": 6.01,
    },
    "GOAT": {
        "drift":        "GOAT-PERP",
        "dydx":         "GOAT-USD",
        "hyperliquid":  "GOAT",
        "sol":          "CzLSujWBLFsSjncfkh59rUFqvafWcY5tzedWJSuypump",
        "eth":          None,
        "base":         None,
        "max_price": 1.35,
    },
    "SPX": {
        "drift":        None,
        "dydx":         "SPX-USD",
        "hyperliquid":  "SPX",
        "sol":          "J3NKxxXZcnNiMjKw9hYb2K4LUxgwB6t1FtPtQVsv3KFr",
        "eth":          "0xe0f63a424a4439cbe457d80e4f4b51ad25b2c56c",
        "base":         "0x50da645f148798f68ef2d7db7c1cb22a6819bb2c",
        "max_price": 1.72,
    },
    "AIXBT": {
        "drift":        None,
        "dydx":         "AIXBT-USD",
        "hyperliquid":  "AIXBT",
        "sol":          "14zP2ToQ79XWvc7FQpm4bRnp9d6Mp1rFfsUW3gpLcRX",
        "eth":          None,
        "base":         "0x4f9fd6be4a90f2620860d680c0d4d5fb53d1a825",
        "max_price": 0.9426,
    },
    "GRIFFAIN": {
        "drift":        False,
        "dydx":         "GRIFFAIN-USD",
        "hyperliquid":  "GRIFFAIN",
        "sol":          "KENJSUYLASHUMfHyy5o4Hp2FdNqZg1AsUPhfH2kYvEP",
        "eth":          None,
        "base":         None,
        "max_price": 0.6249,
    },
    "VIRTUAL": {
        "drift":        False,
        "dydx":         "VIRTUAL-USD",
        "hyperliquid":  "VIRTUAL",
        "sol":          "3iQL8BFS2vE7mww4ehAqQHAsbmRNCrPxizWAT2Zfyr9y",
        "eth":          "0x44ff8620b8ca30902395a7bd3f2407e1a091bf73",
        "base":         "0x0b3e328455c4059eeb9e3f84b5543f74e24e7e1b",
        "max_price": 5.07,
    },
    "VINE": {
        "drift":        False,
        "dydx":         "VINE-USD",
        "hyperliquid":  "VINE",
        "sol":          "6AJcP7wuLwmRYLBNbi825wgguaPsWzPBEHcHndpRpump",
        "eth":          None,
        "base":         None,
        "max_price": 0.4699,
    },
    "BANANA": {
        "drift":        False,
        "dydx":         "BANANA-USD",
        "hyperliquid":  "BANANA",
        "sol":          None,
        "eth":          "0x38e68a37e401f7271568cecaac63c6b1e19130b4",
        "base":         None,
        "max_price": 78.62,
    },
    "CHILLGUY": {
        "drift":        False,
        "dydx":         False,
        "hyperliquid":  "CHILLGUY",
        "sol":          "Df6yfrKC8kZE3KNkrHERKzAetSxbrWeniQfyJY4Jpump",
        "eth":          None,
        "base":         None,
        "max_price": 0.6575,
    }
}